language: java
cache:
  directories:
  - "$HOME/.m2"
install: true
script:
  mvn test
notifications:
  slack:
    on_failure: always
    on_success: change
    rooms:
      secure: Oe/Ym9+gt7hTlwuCGv/RjBO/z0BnBHenL9J+E6yOevaPjaf3SGaHeOdv0buYy8PdmejoxyxMtyRTR5eLPgDbw+TSMJ0OPRbr3F9yez9laT8i9esWEH4EYkQdQNEniBiBFuDd70ZCYYd0q70Qbx3WbMQ0YxoRjT18fNY5A9dv4MFe1yPXPE6zcSKzRAiQAWgBjir5I6qJmL1AjmQAvEBy64yO+jkWbUEEtS9kBPJFSBKpRFp/AEjHMrut00c7FT+Z+8WKiozqK5/I6voHckdf6bC5Y6DWG7mIdw8BDfoxpzefwrCZY8X6KGnmWZmPb8FXxrs9qgdPx7shFnYPxsWwn81H1pk5aGALMcAg+pyK99NNgHCyV5cNIWrw6cSvXiLsDYsTFBUSJ/AWwe1JlgP8tl2HhGEkqBSPy/8dWcIAqP6i1mXAz78hgbU/LAlD3zsa+jc0KlMYPbMceUjgjArucS5yvOnBUKCmAzIfWVvAYXjx0avgOwUqoNmLFk3AP1UHHhfEX0Lz7PpjnvkLmGum6lxQlognEhiy9oIXRsnF++ztSGKemHfGHWyCqOBbgKdZuGSb0JIAbWEupJNG6/zRCYyz0L6wvZlzPre/FVgdxZpCjL4+q5kY8P/zXeCJX/cdM1ZvvlymM4uS8lnMUhEwlrjGGba19660A9eWLXFkj+c=
